### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elifoster** [elifoster/MC-SkillPoints#1]
- [ ] XP system- Started at branch systems-xp
  - [x] Archery XP increase on successful arrow hits
    - [x] Saving XP per player with NBT
  - [x] Melee combat XP increase on successful hits
    - [x] Saving XP per player with NBT
  - [x] Block XP increase on successful blocks
    - [x] Saving XP per player with NBT
  - [ ] Brewing XP increase on successful brews
    - [ ] Saving XP per player with NBT
  - [ ] Enchanting XP increase on successful enchantments
    - [ ] Saving XP per player with NBT
  - [x] Farming XP increase on harvesting and planting
    - [x] Saving XP per player with NBT
  - [ ] Fishing XP increase on successful catches
    - [ ] Saving XP per player with NBT
  - [x] Mining XP increase on ore digging and smelting
    - [x] Saving XP per player with NBT
  - [x] Smithing XP increase on successful Anvil uses
    - [x] Saving XP per player with NBT
  - [ ] Speech XP increase on successful trades
    - [ ] Saving XP per player with NBT
- [ ] Level system
  - [ ] Archery level system
    - [ ] Saving level per player with NBT
  - [ ] Melee combat level system
    - [ ] Saving level per player with NBT
  - [ ] Block XP level system
    - [ ] Saving level per player with NBT
  - [ ] Brewing XP level system
    - [ ] Saving level per player with NBT
  - [ ] Enchanting XP level system
    - [ ] Saving level per player with NBT
  - [ ] Farming XP level system
    - [ ] Saving level per player with NBT
  - [ ] Fishing XP level system
    - [ ] Saving level per player with NBT
  - [ ] Mining XP level system
    - [ ] Saving level per player with NBT
  - [ ] Smithing XP level system
    - [ ] Saving level per player with NBT
  - [ ] Speech XP level system
    - [ ] Saving level per player with NBT
- [ ] Perk system
  - [ ] Saving perks per player with NBT
  - [ ] Archery perks
    - [ ] Sharpshooter
    - [ ] Critical damage
    - [ ] Hard arrows
    - [ ] Piercer
    - [ ] Quick draw
  - [ ] Melee combat perks
    - [ ] Swift swinger
    - [ ] Critical damage
    - [ ] Heavy hitter
    - [x] Strongarm
    - [ ] Crusher
  - [ ] Block XP perks
    - [ ] Block unarmed
    - [ ] Block armed
    - [ ] Block spider bites
    - [ ] Block poison bites
    - [ ] Block booms
  - [ ] Brewing XP perks
    - [ ] Brew bag
    - [ ] Where'd that bottle come from?
    - [ ] Higher ABV
    - [ ] Sticky weapons
    - [ ] Anti-poison
  - [ ] Enchanting XP perks
    - [ ] Double enchantment
    - [ ] Experience whore
    - [ ] Super armor enchanter
    - [ ] Now for the rest
    - [ ] Save the leftovers 
  - [ ] Farming XP perks
    - [ ] Farm feeler
    - [ ] Green thumb
    - [ ] Quick grow
    - [ ] Potato friendly
    - [ ] Animal whisperer
  - [ ] Fishing XP perks
    - [ ] Better bait
    - [ ] 2 fish 1 rod
    - [ ] 3 fish 1 rod
    - [ ] Quick cast
    - [ ] Treasure fishing
  - [ ] Mining XP perks
    - [x] XP farmer
    - [x] Fortune miner
    - [x] Diamond miner
    - [ ] Quick smash
    - [ ] Hidden resources
  - [ ] Smithing XP perks 
    - [x] Stronger metals
    - [ ] Experience whore
    - [x] Delicate touch
    - [ ] Golden touch
    - [ ] Instant gratification
  - [ ] Speech XP perks
    - [ ] Silver tongue
    - [ ] Trading company
    - [ ] Killing is my business
    - [ ] General goods
    - [ ] Always open
- [ ] GUI for gaining perks and viewing levels/xp amounts
- [x] API

**Comment by elifoster** [comment]
Shit. Just realized I should have put that previous commit into a branch. Going to fix that now.

**Comment by elifoster** [comment]
I took a look in the Forge Events and found that for Enchanting and Alchemy we will need to create our own events/hooks/whatevers. For enchanting, it seems that someone tried to get some enchantment event added to MCF, but it never got merged.

See MinecraftForge/MinecraftForge#1622 for that enchantment event. 

Still unsure how we are going to do brewery stuff. @Strikingwolf any ideas?

**Comment by FayeAlephNil** [comment]
Worst case scenario we could ASM into the Brewing stand, and on brew fire an event that we create.

As for a better method of it I'm not sure

**Comment by FayeAlephNil** [comment]
As mentioned in IRC, we could extend/replace instead of ASM for the Brewing/Enchantment

Also, developing an API would be good not just for limiting down on some code replacement, but also for others to use if they so need

**Comment by elifoster** [comment]
Of course. It'll also make us adding native mod integration much, much easier.

**Comment by FayeAlephNil** [comment]
Do you want me to make an ASM TODO for all the things that will need ASM?

**Comment by elifoster** [comment]
Go ahead

**Comment by FayeAlephNil** [comment]
It seems there are brewing and smelting events in Forge, you must have not seen them, check here

https://dl.dropboxusercontent.com/s/h777x7ugherqs0w/forgeevents.html

**Comment by elifoster** [comment]
The brewing event does not contain everything we need. I tried already.

It took me fucking forever, but I found that playerevent in the code. It's not net.minecraftforge.event, it's in net.minecraftforge.common.fml.gameevent

**Comment by FayeAlephNil** [comment]
mhm, the smelting event does have a player ref though.

I took a look at the brewing event and saw it didn't have it to

**Comment by elifoster** [comment]
Indeed it does. I'll finish the mining xp system when I get a chance, probably today.

**Comment by FayeAlephNil** [comment]
Here is a discussion I had with some of the PT members, what are your opinions? http://paste.ee/p/zs2vj

**Comment by FayeAlephNil** [comment]
Also, if you want I can start on the actual skill system, the skeleton of it at the very least.

**Comment by elifoster** [comment]
I'm not see what my opinion should be about tbh. And what do you mean by the skill system? The saving xp stuff? I started it at origin/systems-xp-saving but am having some issues, as I've never fucked with this kind of shit.

**Comment by FayeAlephNil** [comment]
Do you think we should make new Tile Entities and Guis instead of doing the ASM, read the paste log :P and what I mean by the skill system I mean having objects for skills which do certain things when you have a certain amount of xp points, an abstraction on top of all the different skills we will have basically

**Comment by elifoster** [comment]
New stuff might be easier.

And no on the skills. The way it's going to work is you level up your skill when you get a certain amount of xp for that skill. You can open a GUI and give yourself perks if you are the right level. Very similar to skyrim, but without total xp/level and skill points.

**Comment by FayeAlephNil** [comment]
alright, I can do that, if you look at the last commit, that is what I meant :P It is an abstract skeleton with no checking or anything yet, just an xp needed thing.

**Comment by FayeAlephNil** [comment]
Would you like me to make a new branch for the skill system/API?

**Comment by elifoster** [comment]
Yes

**Comment by elifoster** [comment]
Before we work on perks, we need to finish all of the skill stuff, mostly skill-based player-specific XP saving.

**Comment by elifoster** [comment]
Merging systems-xp-saving into systems-xp because having that branch is actually just really fucking stupid.

**Comment by elifoster** [comment]
@Strikingwolf The smelt event appears to only be in 1.8.

**Comment by FayeAlephNil** [comment]
PlayerEvent.ItemSmeltedEvent

It's there

**Comment by elifoster** [comment]
@Strikingwolf Please make sure everything works with Java 6/7. floorDiv is a J8-only feature.

**Comment by FayeAlephNil** [comment]
Alright, I didn't know that floorDiv was J8 only
