### ISSUE TITLE
TODO API

### ISSUE THREAD

**Issue by FayeAlephNil** [elifoster/MC-SkillPoints#4]
- [x] Perk API
  - [x] Able to get level, name, and description from Perks
  - [x] Ability to execute a perk for a given event
  - [x] Ability to add perk groups (skills) that have perks that may activate on certain events
    - [x] Ability to get the name of a skill group
    - [x] Ability to get the list of perks in a group
    - [x] Ability to get get the bus a skill group is on
    - [x] Have a way to execute the perks on a given event (fired by the bus)
    - [x] Ability to get the available perks for a player (in the form of HashMap of xp group to level)
    - [x] Ability to get new perks in the same manner as you can get the available perks
    - [x] Ability to save perks to a player
  - [x] Ability to check if the player has a perk
  - [x] Ability to add a perk to a player
  - [x] Ability to remove a perk from a player
  - [x] Ability to save a perk to a player
- [x] XP Group API
  - [x] Ability to get the name of a group
  - [x] Ability to get the total xp a player has in said group
  - [x] Ability to get the total level of a player in said group
  - [x] Ability to save a player's progress in a group
- [x] Master API
  - [x] Ability to get a skillHandler or xpHandler by name or index
  - [x] Ability to add a skillHandler of xpHandler
  - [x] Ability to save the entire system for a player or List of players
  - [x] Ability to get the available perks for a player
  - [x] Ability to get the new perks for a player as a result of an xp group leveling up
  - [x] Ability to call a method on level up which will update the system
- [x] Have forward-porting of the API as mentioned [here](http://paste.ee/p/rQIXy)
  - [x] Specify a general API interface that will not change and can get certain versions of the API
  - [x] Make a version of that API interface for the beta with extra features

**Comment by FayeAlephNil** [comment]
By the current looks of things i can either get on the API compatibility stuff, or I can go ahead and merge the api branch and work on that later, thoughts?

**Comment by elifoster** [comment]
I think, if the API is fully functional, submit a PR so I can take a look at everything. Then post-review we will merge with master, and you go ahead and work on that stuff later. Keep the branches clean :)

**Comment by FayeAlephNil** [comment]
Alright, it is fully functional, but eventually I'll want to get that compatibility stuff together, preferably before 1.0 release :)

**Comment by FayeAlephNil** [comment]
Rework API because using Event Buses for execution of shit won't work. Will have to let people do that manually

EDIT: (See below)

**Comment by FayeAlephNil** [comment]
Actually I tested it, the current method will work the reason it wasn't working for the GeneralXPHandler was because in the generic I didn't have "extends Event." As for multiple things @elifoster just add multiple methods with the @SubscribeEvent annotation, the event bus should still pick it up.

The one thing there that does need fixing however is the changing of bus() to buses() so that running on multiple EventBuses is possible

**Comment by elifoster** [comment]
alriighty

**Comment by FayeAlephNil** [comment]
Now that I have made this version-compatible, this should be closed, @elifoster ready to merge?

**Comment by elifoster** [comment]
Merge what?

**Comment by elifoster** [comment]
@Strikingwolf I already merged api to systems-xp, why were you pushing to api? :clap: 

Can you please merge api to systems-xp again?

**Comment by FayeAlephNil** [comment]
Merge API into systems-xp again, I was pushing to API because I had one last thing to do to the API, I'll merge again
